"use strict";
const $=id=>document.getElementById(id);let state={networks:[],pending:null,messages:[],current_network:null},tab="首页";
function node(tag,text,parent){const e=document.createElement(tag);if(text)e.textContent=text;if(parent)parent.append(e);return e}
function button(parent,text,fn,cls=""){const e=node("button",text,parent);e.type="button";e.className=cls;e.onclick=fn;return e}
async function send(action,extra={}){if(!window.webxdc){$("status").textContent="请在 Delta Chat 内打开此小应用。";return}const token=window.CONTACT_CONFIG?.token;if(!token){await window.webxdc.sendToChat({text:"小程序"});return}const id=Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,"0")).join("");$("status").textContent="正在准备操作消息。请发送到原机器人私聊；未发送就不会执行。";try{await window.webxdc.sendToChat({text:"联系人小程序 "+JSON.stringify({token,id,action,network:state.current_network,...extra})});$("status").textContent="消息草稿已准备，请确认发送。发送后重新打开，等待机器人结果。"}catch{ $("status").textContent="未能准备消息，请重试。"}}
const command=(command,value="")=>send("command",{command,value});
function form(parent,label,submit){const f=node("form",null,parent);const l=node("label",label,f);const input=node("input",null,l);input.required=true;const b=node("button","继续",f);b.type="submit";f.onsubmit=e=>{e.preventDefault();submit(input.value)}}
function render(){ $("network").textContent=state.networks.map(n=>n.name+" · "+n.nickname).join(" / ")||"加入一个网络，开始认识彼此";$("result").replaceChildren();if(state.messages.length){node("h2","机器人反馈",$("result"));state.messages.forEach(m=>node("div",m,$("result")).className="reply" )}const w=$("wizard");w.replaceChildren();const p=state.pending;if(p){node("h2","下一步",w);node("p","请先阅读上方机器人反馈，再做选择。联系人名片只会在接收方同意后发送。",w);const reply=value=>send("reply",{step:p.token,value});const choices={guide_privacy:["同意并加入","不同意"],guide_contact_choice:["使用当前 Delta Chat 地址","手动填写地址","稍后设置"],guide_privacy_choice:["公开资料并接收申请","隐藏资料但接收申请","隐藏资料并暂停申请"],guide_next:["按昵称找人","按编号找人","查看我的资料","暂时结束"],guide_incoming_request:["同意并接收名片","拒绝","屏蔽"],send_vcard_request:["确认发送申请","取消"],send_request:["确认本次分享","取消"],accept_request:["确认交换","取消"],join:["同意加入","取消"],leave:["确认退出","取消"],delete:["确认删除个人数据","取消"],rotate_code:["确认更换","取消"]};if(choices[p.action])choices[p.action].forEach((t,i)=>button(w,t,()=>reply(String(i+1)),i?"secondary":""));else if(p.action==="guide_choose_target")(state.choices||[]).forEach(c=>button(w,c.label,()=>reply(c.value),"secondary"));else{const labels={guide_join_code:"输入管理员给你的加入码",guide_nickname:"你希望大家怎么称呼你？",guide_search:"对方昵称或成员编号",guide_member_code:"对方成员编号",guide_reason:"简单介绍你的联系原因",guide_contact_manual:"愿意分享的 Delta Chat 地址",guide_accept_contact:"愿意分享的 Delta Chat 地址"};form(w,labels[p.action]||"填写上方提示要求的内容",reply)}button(w,"取消当前步骤",()=>command("取消"),"secondary")}
const page=$("page");page.replaceChildren();node("h2",tab,page);
if(tab==="首页"){node("p","加入网络 → 找到成员 → 对方同意 → 接收联系人名片",page);button(page,"开始 / 继续引导",()=>send("start"));button(page,"刷新状态",()=>send("refresh"),"secondary");node("p","联系人名片由机器人自动生成，只在接收方同意后发送。",page)}
if(tab==="找人"){form(page,"输入昵称或成员编号",v=>send("search",{value:v}));node("p","也可以回到首页使用逐步引导，点击搜索结果选择成员。本人可以被自己找到，不能向自己发申请。",page)}
if(tab==="申请"){button(page,"查看收到和发出的申请",()=>command("我的申请"));for(const r of state.requests||[]){const card=node("div",null,page);node("p",`${r.sender} → ${r.recipient}`,card);node("p",r.reason,card);const names={pending_target:"等待同意",processing:"正在交换",completed:"已交换联系方式",rejected:"已结束",withdrawn:"已撤销",expired:"已过期",invalid:"已失效"};node("small",names[r.status]||r.status,card);if(r.status==="pending_target")for(const c of r.direction==="incoming"?["同意申请","拒绝申请"]:["撤销申请"])button(card,c,()=>command(c,r.public_id),"secondary")}node("p","申请有效期为 7 天。同意前会再次展示你要分享的联系方式。交换成功不代表已经完成好友添加。",page)}
if(tab==="我的"){button(page,"我的资料",()=>command("我的资料"));button(page,"我的网络",()=>command("我的网络"),"secondary");button(page,"加入新网络",()=>send("join"),"secondary");for(const c of ["编辑昵称","编辑介绍"])form(page,c,v=>command(c,v));for(const n of state.networks)button(page,"切换到 "+n.name,()=>command("切换网络",n.public_id),"secondary");for(const c of ["公开资料","隐藏资料","接收申请","暂停申请"])button(page,c,()=>command(c),"secondary");const d=node("details",null,page);node("summary","屏蔽、举报与数据管理",d);for(const c of ["屏蔽","解除屏蔽","举报"])form(d,c+"：成员编号"+(c==="举报"?" + 空格 + 原因":""),v=>command(c,v));button(d,"屏蔽列表",()=>command("屏蔽列表"),"secondary");for(const c of ["退出网络","删除我的数据"])button(d,c,()=>command(c),"danger");node("p","机器人服务端可处理发给它的数据。已交付的联系人名片和小应用历史无法从对方设备收回。",d)}
if(tab==="我的"&&state.admin_role){const admin=node("details",null,page);node("summary",state.admin_role==="system"?"系统管理":"当前网络管理",admin);node("p","所有操作由机器人重新校验权限。网络管理员仅能管理自己负责的网络。",admin);for(const c of ["网络概况","成员列表","查看加入码","更换加入码","停用加入","恢复加入","举报列表","管理记录"])button(admin,c,()=>command(c),"secondary");for(const [c,l] of [["移除成员","成员编号"],["封禁成员","成员编号和原因"],["解除封禁","成员编号"],["处理举报","举报编号和处理结果"]])form(admin,c+"："+l,v=>command(c,v));if(state.admin_role==="system"){for(const c of ["创建网络","任命管理员","撤销管理员","停用网络","恢复网络","修改网络名称"])form(admin,c+"（具体填写规则可点管理帮助）",v=>command(c,v));button(admin,"网络列表",()=>command("网络列表"),"secondary")}button(admin,"管理帮助",()=>command("管理"),"secondary")}
$("nav").replaceChildren();for(const name of ["首页","找人","申请","我的"])button($("nav"),name,()=>{tab=name;render()},name===tab?"active":"")}
render();if(window.webxdc)window.webxdc.setUpdateListener(update=>{const p=update.payload;if(!p||p.type!=="contact-state"||!Array.isArray(p.networks)||!Array.isArray(p.messages))return;state={...p,messages:p.messages.length?p.messages:state.messages};$("status").textContent="已收到状态更新。最终操作结果请核对机器人私聊消息。";render()},0);
