FROM python:3.12-slim
ENV PIP_DEFAULT_TIMEOUT=120
WORKDIR /app
COPY dist/delta_contact_network_bot-0.7.5-py3-none-any.whl /dist/
COPY tests ./tests
RUN pip install --no-cache-dir /dist/delta_contact_network_bot-0.7.5-py3-none-any.whl pytest ruff httpx
CMD ["pytest"]
