"use strict";
/* Pure Webxdc prototype. All public state is replicated; contacts use ECDH/AES-GCM envelopes. */
const $=id=>document.getElementById(id), encoder=new TextEncoder(), decoder=new TextDecoder();
const STORE="contact-network-p2p-v1", now=()=>new Date().toISOString(), id=()=>crypto.randomUUID();
let tab="首页", state={network:null,members:{},requests:{},blocks:{}}, events=[];
const local=JSON.parse(localStorage.getItem(STORE)||"{}");
const save=()=>localStorage.setItem(STORE,JSON.stringify(local));
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))), unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const canonical=v=>JSON.stringify(sort(v));
function sort(v){if(Array.isArray(v))return v.map(sort);if(v&&typeof v==="object")return Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])]));return v;}
async function digest(value){return b64(await crypto.subtle.digest("SHA-256",encoder.encode(value)));}
async function importKey(jwk,usage){return crypto.subtle.importKey("jwk",jwk,{name:"ECDSA",namedCurve:"P-256"},true,usage);}
async function identity(){if(local.identity)return local.identity;const sign=await crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]), box=await crypto.subtle.generateKey({name:"ECDH",namedCurve:"P-256"},true,["deriveKey"]);local.identity={signPrivate:await crypto.subtle.exportKey("jwk",sign.privateKey),signPublic:await crypto.subtle.exportKey("jwk",sign.publicKey),boxPrivate:await crypto.subtle.exportKey("jwk",box.privateKey),boxPublic:await crypto.subtle.exportKey("jwk",box.publicKey)};save();return local.identity;}
async function sign(data){const me=await identity(), key=await importKey(me.signPrivate,["sign"]);return b64(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},key,encoder.encode(canonical(data))));}
async function verify(data,sig,pub){try{const key=await importKey(pub,["verify"]);return crypto.subtle.verify({name:"ECDSA",hash:"SHA-256"},key,unb64(sig),encoder.encode(canonical(data)));}catch{return false;}}
async function encryptFor(pub,plain){const me=await identity(), mine=await crypto.subtle.importKey("jwk",me.boxPrivate,{name:"ECDH",namedCurve:"P-256"},false,["deriveKey"]), theirs=await crypto.subtle.importKey("jwk",pub,{name:"ECDH",namedCurve:"P-256"},false,[]), key=await crypto.subtle.deriveKey({name:"ECDH",public:theirs},mine,{name:"AES-GCM",length:256},false,["encrypt"]), iv=crypto.getRandomValues(new Uint8Array(12));return {iv:b64(iv),data:b64(await crypto.subtle.encrypt({name:"AES-GCM",iv},key,encoder.encode(plain)))};}
async function decryptFrom(pub,envelope){try{const me=await identity(), mine=await crypto.subtle.importKey("jwk",me.boxPrivate,{name:"ECDH",namedCurve:"P-256"},false,["deriveKey"]), theirs=await crypto.subtle.importKey("jwk",pub,{name:"ECDH",namedCurve:"P-256"},false,[]), key=await crypto.subtle.deriveKey({name:"ECDH",public:theirs},mine,{name:"AES-GCM",length:256},false,["decrypt"]);return decoder.decode(await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(envelope.iv)},key,unb64(envelope.data)));}catch{return null;}}
function me(){return window.webxdc?.selfAddr||"浏览器演示用户";} function name(){return window.webxdc?.selfName||"本地用户";}
function node(tag,text,parent){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(parent)parent.append(e);return e;} function button(p,t,fn,cls=""){const b=node("button",t,p);b.type="button";b.className=cls;b.onclick=fn;return b;}
function form(p,fields,submit){const f=node("form",undefined,p), values={};for(const spec of fields){const l=node("label",spec.label,f), input=node(spec.long?"textarea":"input",undefined,l);input.required=spec.required!==false;input.placeholder=spec.placeholder||"";input.value=spec.value||"";values[spec.key]=input;}const b=node("button","确认",f);b.type="submit";f.onsubmit=async e=>{e.preventDefault();await submit(Object.fromEntries(Object.entries(values).map(([k,v])=>[k,v.value.trim()])))};}
async function send(kind,body={},admin=false){if(!window.webxdc){$("status").textContent="请在支持 Webxdc 的 Delta Chat 聊天中打开。";return;}const event={v:1,id:id(),kind,actor:me(),at:now(),body};event.sig=await sign(event);if(admin){event.adminSig=await sign({kind:event.kind,body:event.body,at:event.at});}window.webxdc.sendUpdate({payload:event,summary:"联系人网络有新动态"},"");apply(event);render();}
async function valid(event){if(!event||event.v!==1||!event.kind||!event.actor||!event.sig)return false;const {sig,adminSig,...unsigned}=event;if(event.kind==="bootstrap")return !state.network&&event.body?.admin?.signPublic&&await verify(unsigned,sig,event.body.admin.signPublic);if(event.kind==="join"){if(!state.network||event.body?.codeHash!==state.network.codeHash||state.members[event.actor]||!event.body?.signPublic)return false;return verify(unsigned,sig,event.body.signPublic);}const member=state.members[event.actor];if(!member||!(await verify(unsigned,sig,member.signPublic)))return false;if(event.kind.startsWith("admin-")){if(event.actor!==state.network.admin||!adminSig)return false;return verify({kind:event.kind,body:event.body,at:event.at},adminSig,state.members[event.actor].signPublic);}return true;}
function reset(){state={network:null,members:{},requests:{},blocks:{}};}
async function replay(){const history=events;events=[];reset();for(const e of history){if(await valid(e))apply(e,false);}render();}
function apply(e,draw=true){if(events.some(x=>x.id===e.id))return;events.push(e);const b=e.body;
 if(e.kind==="bootstrap"){state.network={name:b.name,codeHash:b.codeHash,admin:e.actor,createdAt:e.at};state.members[e.actor]={...b.admin,active:true};}
 if(e.kind==="join"&&state.network&&b.codeHash===state.network.codeHash&&!state.members[e.actor])state.members[e.actor]={...b,active:true};
 if(e.kind==="profile"&&state.members[e.actor])state.members[e.actor]={...state.members[e.actor],nickname:b.nickname,bio:b.bio,discoverable:b.discoverable};
 if(e.kind==="leave"&&state.members[e.actor])state.members[e.actor].active=false;
 if(e.kind==="block")state.blocks[`${e.actor}:${b.target}`]=true;
 if(e.kind==="request"&&state.members[b.to]&&state.members[e.actor]&&e.actor!==b.to)state.requests[e.id]={id:e.id,from:e.actor,to:b.to,status:"pending",reason:b.reason,contact:b.contact,at:e.at};
 if(e.kind==="reject"&&state.requests[b.request])state.requests[b.request].status="rejected";
 if(e.kind==="withdraw"&&state.requests[b.request])state.requests[b.request].status="withdrawn";
 if(e.kind==="accept"&&state.requests[b.request]){state.requests[b.request].status="accepted";state.requests[b.request].replyContact=b.contact;}
 if(e.kind==="admin-ban"&&state.members[b.target])state.members[b.target].active=false;
 if(draw)render();}
async function receive(update){const e=update.payload;if(!e||events.some(x=>x.id===e.id))return;if(await valid(e)){apply(e);$("status").textContent="已同步网络更新。";}}
function activeMembers(){return Object.entries(state.members).filter(([,m])=>m.active);}
async function setup(v){const mine=await identity(), codeHash=await digest(v.code);await send("bootstrap",{name:v.name,codeHash,admin:{nickname:v.nickname||name(),bio:"网络管理员",discoverable:true,signPublic:mine.signPublic,boxPublic:mine.boxPublic}},true);}
async function join(v){if(await digest(v.code)!==state.network.codeHash){$("status").textContent="加入码不正确。";return;}const mine=await identity();await send("join",{codeHash:state.network.codeHash,nickname:v.nickname,bio:v.bio,discoverable:v.discoverable,signPublic:mine.signPublic,boxPublic:mine.boxPublic});}
async function request(target,v){const recipient=state.members[target], mine=await identity();if(!local.contact){$("status").textContent="请先在“我的”里保存要分享的 Delta Chat 地址。";tab="我的";render();return;}await send("request",{to:target,reason:await encryptFor(recipient.boxPublic,v.reason),contact:await encryptFor(recipient.boxPublic,local.contact)});}
async function accept(req){if(!local.contact){tab="我的";$("status").textContent="请先保存要分享的 Delta Chat 地址。";render();return;}const requester=state.members[req.from];await send("accept",{request:req.id,contact:await encryptFor(requester.boxPublic,local.contact)});}
function mineRequests(){return Object.values(state.requests).filter(r=>r.from===me()||r.to===me());}
async function render(){const p=$("page");p.replaceChildren();$("title").textContent=state.network?.name||"联系人网络";$("subtitle").textContent=state.network?`${activeMembers().length} 位活跃成员 · 不需要机器人消息`:"管理员首次设置后，请把本 .xdc 分享至网络群聊";
 if(!state.network){node("h2","创建网络",p);node("p","首次创建者会成为管理员。请在创建完成后再把小应用分享给成员。",p);form(p,[{key:"name",label:"网络名称",placeholder:"例如：读书会"},{key:"code",label:"管理员自定义加入码",placeholder:"可使用中文、空格或 emoji"},{key:"nickname",label:"管理员昵称",value:name()}],setup);node("p","加入码的哈希会同步给成员端，用于本地验证；请设置长度足够且不公开的加入码。",p).className="muted";return;}
 if(!state.members[me()]){node("h2","加入网络",p);node("p","资料默认公开可查找；联系方式不会公开，只在你同意申请后加密交给对方。",p);form(p,[{key:"code",label:"加入码"},{key:"nickname",label:"昵称",value:name()},{key:"bio",label:"一句介绍",required:false,long:true},{key:"discoverable",label:"允许被搜索（输入 是 或 否）",value:"是"}],async v=>join({...v,discoverable:v.discoverable!=="否"}));return;}
 if(tab==="首页"){node("h2","欢迎回来",p);node("p","找人、申请和状态更新都会直接在小应用内同步。联系人地址以端到端加密信封发送，其他成员无法读取。",p);button(p,"查看我的资料",()=>{tab="我的";render();});}
 if(tab==="找人"){node("h2","找人",p);const search=node("input",undefined,p);search.placeholder="按昵称或介绍搜索";const list=node("div",undefined,p);const show=()=>{list.replaceChildren();const q=search.value.trim().toLowerCase();for(const [who,m] of activeMembers().filter(([who,m])=>m.discoverable&&(m.nickname+" "+(m.bio||"")).toLowerCase().includes(q))){const c=node("div",undefined,list);c.className="card";node("h3",m.nickname+(who===me()?"（本人）":""),c);node("p",m.bio||"暂无介绍",c);if(who!==me())button(c,"申请联系",()=>askRequest(who,m.nickname));}};search.oninput=show;show();}
 if(tab==="申请"){node("h2","联系申请",p);const requests=mineRequests();if(!requests.length)node("p","还没有申请。",p);for(const r of requests){const other=r.from===me()?r.to:r.from,m=state.members[other],c=node("div",undefined,p);c.className="card";node("h3",(r.from===me()?"发给 ":"来自 ")+(m?.nickname||"成员"),c);node("p",r.status==="pending"?"等待处理":r.status==="accepted"?"双方已授权交换":"已结束",c);if(r.to===me()&&r.status==="pending"){const reason=await decryptFrom(m.boxPublic,r.reason);node("p","原因："+(reason||"仅你可解密"),c);button(c,"同意并分享我的地址",()=>accept(r));button(c,"拒绝",()=>send("reject",{request:r.id}),"secondary");}if(r.from===me()&&r.status==="pending")button(c,"撤销",()=>send("withdraw",{request:r.id}),"secondary");if(r.status==="accepted"){const encrypted=r.from===me()?r.replyContact:r.contact, sender=state.members[other];const contact=await decryptFrom(sender.boxPublic,encrypted);node("p",contact?"对方授权地址："+contact:"正在解密或地址不可用",c);}}}
 if(tab==="我的"){const m=state.members[me()];node("h2","我的资料",p);node("p",`${m.nickname} · ${m.discoverable?"可被搜索":"隐藏资料"}`,p);form(p,[{key:"nickname",label:"昵称",value:m.nickname},{key:"bio",label:"介绍",value:m.bio||"",required:false,long:true},{key:"discoverable",label:"允许被搜索（是 / 否）",value:m.discoverable?"是":"否"}],v=>send("profile",{nickname:v.nickname,bio:v.bio,discoverable:v.discoverable!=="否"}));form(p,[{key:"contact",label:"仅保存在本设备的 Delta Chat 地址",value:local.contact||"",required:false}],async v=>{local.contact=v.contact;save();$("status").textContent="地址已保存在本设备，未同步给任何成员。";});const d=node("details",undefined,p);node("summary","网络与安全说明",d);node("p",`你的应用内 ID：${me()}`,d).className="muted";node("p","清除应用数据会丢失本地私钥和加密联系人。联系人网络无法从其他成员设备删除已同步的历史记录。",d).className="danger-note";button(d,"退出网络",()=>send("leave",{}),"danger");if(me()===state.network.admin){const a=node("details",undefined,p);node("summary","管理员",a);node("p","管理员可封禁成员。管理员身份依赖本设备保存的密钥。",a);for(const [who,m] of activeMembers().filter(([who])=>who!==me()))button(a,"封禁 "+m.nickname,()=>send("admin-ban",{target:who},true),"danger");}}
 $("nav").replaceChildren();for(const label of ["首页","找人","申请","我的"])button($("nav"),label,()=>{tab=label;render();},label===tab?"active":"");}
function askRequest(who,nickname){const p=$("page");p.replaceChildren();node("h2","联系 "+nickname,p);node("p","你的地址会端到端加密，只交给对方；其他网络成员无法读取。",p);form(p,[{key:"reason",label:"联系理由",long:true}],v=>request(who,v));}
if(window.webxdc)window.webxdc.setUpdateListener(receive,0).then(()=>{$("status").textContent="已同步。所有按钮直接提交 Webxdc 更新。";render();});else render();
